name: TaskMaster CI/CD

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  frontend:
    name: Frontend - Bun & Vitest
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: frontend/TaskMasterApp

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1

      - name: Install dependencies
        run: bun install

      - name: Run frontend tests
        run: bun test

      - name: Build frontend
        run: bun run build

  backend:
    name: Backend - Django
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: backend

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Cache pip dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install django-filter  # Añadido explícitamente

      - name: Run backend migrations
        run: |
          python manage.py makemigrations
          python manage.py migrate

      - name: Run backend tests
        run: |
          echo "Running Django tests..."
          python manage.py test users